on:
    push:
      branches:
        - trunk
jobs:
    push_markdown_job:
      runs-on: ubuntu-latest
      name: Push Markdown to Notion
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Push Markdown to Notion
          uses: MathieuLamiot/push-md-to-notion@main
          id: push_markdown
          with:
            notion-token: ${{ secrets.NOTION_TOKEN }}